<a href="https://colab.research.google.com/github/zainameen335/weather_forecast_ML/blob/main/WeatherForecast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [133]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [134]:
df = pd.read_csv("weatherAUS.csv")
df.head()
df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Date           145460 non-null  object 
 1   Location       145460 non-null  object 
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object 
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object 
 10  WindDir3pm     141232 non-null  object 
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null

In [135]:
features = df.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
features
results = df.iloc[:,-1].values
results = results.reshape(-1,1)
results

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       [nan]], dtype=object)

In [136]:
impute = SimpleImputer(missing_values=np.nan,strategy="most_frequent")
features = impute.fit_transform(features)
results = impute.fit_transform(results)
features
results

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       ['No']], dtype=object)

In [137]:
le = LabelEncoder()
encoded_data = [0, 4, 6, 7, -1]
for col in encoded_data:
  features[:, col] = le.fit_transform(features[:, col])
features
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
features[:,0] = le1.fit_transform(features[:,0])
le2 = LabelEncoder()
features[:,4] = le2.fit_transform(features[:,4])
le3 = LabelEncoder()
features[:,6] = le3.fit_transform(features[:,6])
le4 = LabelEncoder()
features[:,7] = le4.fit_transform(features[:,7])
le5 = LabelEncoder()
features[:,-1] = le5.fit_transform(features[:,-1])
le6 = LabelEncoder()
results[:,-1] = le6.fit_transform(results[:,-1])

print(features)
print(results)



[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]
 [41 14.9 20.0 ... 15.0 20.9 0]]
[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [138]:
sc = StandardScaler()
features = sc.fit_transform(features)
features

array([[-1.53166617,  0.19132753, -0.04135977, ..., -0.01407077,
         0.02310362, -0.52979545],
       [-1.53166617, -0.75105231,  0.26874452, ...,  0.03244663,
         0.387799  , -0.52979545],
       [-1.53166617,  0.11279588,  0.35331842, ...,  0.62166712,
         0.22733303, -0.52979545],
       ...,
       [ 1.20928479, -1.06517892,  0.52246622, ..., -0.69632607,
         0.65037966, -0.52979545],
       [ 1.20928479, -0.68822699,  0.53656187, ..., -0.29317521,
         0.63579185, -0.52979545],
       [ 1.20928479,  0.42692249, -0.45013361, ..., -0.30868102,
        -0.10818671, -0.52979545]])

In [139]:
x_train,x_test,y_train,y_test = train_test_split(features,results,test_size=0.2,random_state=0)
y_train = y_train.ravel().astype(int)
y_test = y_test.ravel().astype(int)


In [140]:
clasifier = RandomForestClassifier(n_estimators=150,
                                   class_weight='balanced',
                                   max_depth=12,
                                   min_samples_leaf=5,
                                   random_state=0)
clasifier.fit(x_train,y_train)



RandomForestClassifier(class_weight='balanced', max_depth=12,
                       min_samples_leaf=5, n_estimators=150, random_state=0)

In [141]:
clasifier.score(x_train,y_train)

0.8508352811769558

In [142]:
print(y_test)


[1 1 0 ... 1 0 0]


In [143]:
y_test = y_test.reshape(-1,1)
print(y_test)

[[1]
 [1]
 [0]
 ...
 [1]
 [0]
 [0]]


In [144]:
y_predict = clasifier.predict(x_test)
print(y_predict)

[0 1 0 ... 1 0 0]


In [145]:
y_predict = le6.inverse_transform(y_predict)
print(y_predict)

['No' 'Yes' 'No' ... 'Yes' 'No' 'No']


In [146]:
y_test = le6.inverse_transform(y_test)
print(y_test)

['Yes' 'Yes' 'No' ... 'Yes' 'No' 'No']


/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [147]:
y_test = y_test.reshape(-1,1)
y_predict = y_predict.reshape(-1,1)

In [148]:
df_2 = np.concatenate((y_test,y_predict), axis=1)
dataframe = pd.DataFrame(df_2, columns=["Rain on tomorrow","Prediction of rain"])
print(dataframe)

      Rain on tomorrow Prediction of rain
0                  Yes                 No
1                  Yes                Yes
2                   No                 No
3                   No                Yes
4                   No                 No
...                ...                ...
29087               No                Yes
29088               No                 No
29089              Yes                Yes
29090               No                 No
29091               No                 No

[29092 rows x 2 columns]


In [149]:
accuracy_score(y_test, y_predict)

0.8192286539254778

In [150]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_predict, target_names=['No', 'Yes']))

              precision    recall  f1-score   support

          No       0.91      0.85      0.88     22726
         Yes       0.57      0.72      0.63      6366

    accuracy                           0.82     29092
   macro avg       0.74      0.78      0.76     29092
weighted avg       0.84      0.82      0.83     29092

